apiVersion: apps/v1
kind: Deployment
metadata:
  name: adaptive-rag-app
  labels:
    app: adaptive-rag-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adaptive-rag-app
  template:
    metadata:
      labels:
        app: adaptive-rag-app
    spec:
      # Target x86 instances
      nodeSelector:
        node.kubernetes.io/instance-type: t3.micro
      containers:
      - image: ECR_REPO_URL/adaptive-rag-app
        name: adaptive-rag-app
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "128Mi"  # Reduced for t3.micro (1GB RAM)
            cpu: "50m"       # Reduced for t3.micro (2 vCPU)
          limits:
            memory: "256Mi"  # Conservative limit
            cpu: "100m"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: adaptive-rag-secret
              key: openai-api-key
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: adaptive-rag-secret
              key: tavily-api-key
        volumeMounts:
        - name: chroma-pv-storage
          mountPath: /app/chroma_db_uploaded
      volumes:
      - name: chroma-pv-storage
        persistentVolumeClaim:
          claimName: adaptive-rag-pvc