apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  storageClassName: gp2 # Or gp3, io1, etc. - ensure this storage class is available in your EKS cluster
  resources:
    requests:
      storage: 5Gi # Request 5 GB of storage (adjust as needed)
