apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
type: Opaque
data:
  # Base64 encoded values of your API keys
  # Example: echo -n "sk-proj-..." | base64
  USER_AGENT: myagent
  openai-api-key: c2stcHJvai1Sa2puY3NJNmlfOWFyVncwVGNmeHFYajNWSThQZEU0b2hjUkZyRzNhbFBsejk2RWIxdTJTdXBQNjRyLUJ4MkZiQkVvdFUwc2xDc1QzQmxia0ZKME1oZm9acmZhZEMxSXNMQ0FJVE0tblZHTkE1U2RNMTlGZDJoWXN1UjBXX2RSaEdHSHVSbzhkYWx2eTlkU3dQLXJDWVB5dTgyQUE=
  tavily-api-key: dHZseS1kZXYtV1p0OVduVWxublQxR1hjNW53Zk1rUUR2eGZJamNaOUs=
